#!/usr/bin/env node
/*
 * Copies the invitation film's artwork code (a Remotion project) into the website.
 *
 *   npm run sync:film                       # FILM_SRC defaults to C:\AI-Video-Studio\motion-film
 *   FILM_SRC=/path/to/motion-film npm run sync:film
 *
 * Starting from ENTRIES, it follows relative imports and copies exactly that closure of
 * motion-film/src into frontend/src/film/vendor/, replacing the old copy. The film stays the
 * source of truth: edit the art there, then re-run this script.
 *
 * Two modules are swapped for site versions (see frontend/src/film/overrides/):
 *   theme/fonts.ts  - web @font-face instead of @remotion/fonts
 *   data/i18n.ts    - English only (the site does not show Hindi)
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';import { dirname, join, posix, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const FILM = resolve(process.env.FILM_SRC ?? 'C:\\AI-Video-Studio\\motion-film');
const SRC = join(FILM, 'src');
const DEST = join(ROOT, 'frontend', 'src', 'film', 'vendor');
const FONTS_DEST = join(ROOT, 'frontend', 'src', 'film', 'fonts');

const ENTRIES = [
  'scenes/EngagementScene.tsx',
  'scenes/HaldiMehendiScene.tsx',
  'scenes/SangeetScene.tsx',
  'scenes/SehraScene.tsx',
  'scenes/BaraatScene.tsx',
  'scenes/JaimaalScene.tsx',
  'scenes/LunchScene.tsx',
  'scenes/PhereScene.tsx',
  'scenes/VidaiScene.tsx',
  'scenes/ReceptionScene.tsx',
  'scenes/types.ts',
  'characters/Character.tsx',
  'characters/cast.ts',
  'props/EntrancePanels.tsx',
  'ornaments/Monogram.tsx',
  'ornaments/OrnateCorner.tsx',
  'paper/PaperDefs.tsx',
  'kit/EventTitle.tsx',
  'theme/palette.ts',
  'data/defaults.ts',
  'data/credits.generated.json',
  'film/timeline.ts',
];

/** Film modules replaced by a re-export of a site override (path relative to vendor/). */
const OVERRIDES = {
  'theme/fonts.ts': '../../overrides/fonts',
  'data/i18n.ts': '../../overrides/i18n',
};

/**
 * Exact-text edits for film code that is fine inside a render but not on a shared web page.
 * The sync fails if a pattern is no longer found, so a changed film file is never patched blindly.
 */
const PATCHES = {
  // A global `* { letter-spacing }` reset protects Devanagari in the film; on the site it would
  // flatten the letter-spacing of every label on the page. The site shows no Devanagari.
  'stage/Stage.tsx': [['<style>{"* { letter-spacing: normal !important; }"}</style>', '']],
};

/** Latin display faces the scenes use that the site does not already ship. */
const FONTS = ['Marcellus-400.woff2', 'IBMPlexMono-400.woff2', 'IBMPlexMono-600.woff2', 'PressStart2P-400.woff2'];

const ALLOWED_PACKAGES = new Set(['react', 'remotion', 'zod', 'qrcode']);

if (!existsSync(SRC)) {
  console.error(`motion-film source not found at ${SRC}. Set FILM_SRC to the motion-film folder.`);
  process.exit(1);
}

const IMPORT_RE = /(?:import|export)\s+(?:[^'"]*?\s+from\s+)?["']([^"']+)["']|import\(\s*["']([^"']+)["']\s*\)/g;

const resolveModule = (fromRel, spec) => {
  const base = posix.normalize(posix.join(posix.dirname(fromRel), spec));
  for (const cand of [base, `${base}.ts`, `${base}.tsx`, `${base}/index.ts`, `${base}/index.tsx`]) {
    if (existsSync(join(SRC, cand)) && statSync(join(SRC, cand)).isFile()) return cand;
  }
  throw new Error(`Cannot resolve "${spec}" imported from ${fromRel}`);
};

const seen = new Set();
const packages = new Set();
const queue = [...ENTRIES];
while (queue.length) {
  const rel = queue.shift();
  if (seen.has(rel)) continue;
  seen.add(rel);
  if (rel in OVERRIDES || rel.endsWith('.json')) continue;
  const code = readFileSync(join(SRC, rel), 'utf8');
  for (const m of code.matchAll(IMPORT_RE)) {
    const spec = m[1] ?? m[2];
    if (spec.startsWith('.')) queue.push(resolveModule(rel, spec));
    else packages.add(spec.split('/').slice(0, spec.startsWith('@') ? 2 : 1).join('/'));
  }
}

const unexpected = [...packages].filter((p) => !ALLOWED_PACKAGES.has(p));
if (unexpected.length) {
  console.error(`The film code now imports packages the site does not provide: ${unexpected.join(', ')}`);
  process.exit(1);
}

// Build every output first so a failed patch leaves the existing copy untouched.
const files = [...seen].sort();
const outputs = files.map((rel) => {
  if (rel.endsWith('.json')) return [rel, readFileSync(join(SRC, rel))];
  const header =
    `// @ts-nocheck -- type-checked in the motion-film project, not here.\n` +
    `// Generated by scripts/sync-film.mjs from motion-film/src/${rel}. Edit it there, then run \`npm run sync:film\`.\n`;
  let body = rel in OVERRIDES ? `export * from '${OVERRIDES[rel]}';\n` : readFileSync(join(SRC, rel), 'utf8');
  for (const [from, to] of PATCHES[rel] ?? []) {
    if (!body.includes(from)) {
      console.error(`Patch for ${rel} no longer applies (text not found): ${from}`);
      process.exit(1);
    }
    body = body.replace(from, to);
  }
  return [rel, header + body];
});

// Empty the folder rather than removing it: on Windows an open handle on the folder itself
// (an editor or a shell sitting in it) makes removing the directory fail.
mkdirSync(DEST, { recursive: true });
for (const entry of readdirSync(DEST)) rmSync(join(DEST, entry), { recursive: true, force: true });
for (const [rel, content] of outputs) {
  const out = join(DEST, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, content);
}

mkdirSync(FONTS_DEST, { recursive: true });
for (const f of FONTS) copyFileSync(join(FILM, 'public', 'fonts', f), join(FONTS_DEST, f));

console.log(`Synced ${files.length} modules from ${FILM} into ${relative(ROOT, DEST)}`);
console.log(`Packages used: ${[...packages].sort().join(', ')}`);
